

// the "try" statement lets you test a block of code for errors.

// the "catch" statement lets you handle the error.

// the "throw" statement lets you create custom errors.

// the "finally" statement lets you execute code, after try and catch,
// regardless of the result.




// Errors Will Happen!!!

try{
    conssole.log("hello world");
}
catch(err) {
    console.log(err.message);
}